name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-lint-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      # not tests today
      # - name: Run tests
      #   run: npm run test

      - name: Build Docker image
        run: docker build -t nuxt-app .

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker to use gcloud
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Tag Docker image
        run: docker tag nuxt-app us-central1-docker.pkg.dev/ntalks-466823/gcr.io/nuxt-app

      - name: Push Docker image to Artifact Registry
        run: docker push us-central1-docker.pkg.dev/ntalks-466823/gcr.io/nuxt-app

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy nuxt-app \
            --image us-central1-docker.pkg.dev/ntalks-466823/gcr.io/nuxt-app \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated